VC9 TUNDRA_NO_BOOST: Fix error C2440: '<function-style-cast>' : cannot convert from 'u32' to 'QVariant' No constructor could take the source type, or constructor overload resolution was ambiguous